# Generated by Django 4.2.21 on 2025-05-29 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_task_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='project_type',
            field=models.CharField(choices=[('Private', 'Private'), ('Public', 'Public')], default='Public', max_length=8),
        ),
    ]
