# Generated by Django 4.2.21 on 2025-05-29 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_user_task_user_alter_task_deadline'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
