# Generated by Django 4.2.21 on 2025-05-30 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('In Queue', 'In Queue'), ('In Progress', 'In Progress'), ('Complete', 'Complete')], default='In Queue', max_length=12),
        ),
    ]
