# Generated by Django 4.2.21 on 2025-05-30 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_task_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='project',
            field=models.CharField(default='project1', max_length=100),
        ),
    ]
