# Generated by Django 4.2.21 on 2025-05-30 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_task_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='Filter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority_filter', models.CharField(choices=[('None', 'None'), ('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], default='None', max_length=100)),
                ('status_filter', models.CharField(choices=[('None', 'None'), ('In Queue', 'In Queue'), ('In Progress', 'In Progress'), ('Complete', 'Complete')], default='None', max_length=100)),
            ],
        ),
    ]
