# Generated by Django 4.2.21 on 2025-05-30 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_project_task_priority'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='project_type',
        ),
        migrations.AddField(
            model_name='project',
            name='project_description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='project',
            name='project_type',
            field=models.CharField(choices=[('Private', 'Private'), ('Public', 'Public')], default='Public', max_length=10),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_name',
            field=models.CharField(default='project1', max_length=100),
        ),
    ]
